# Generated by Django 5.0.2 on 2024-03-01 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domotizacion_api', '0003_ubicaciones_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domotizacion_api.ubicaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domotizacion_api.dispositivos')),
            ],
        ),
    ]
